/* ------------------------------------------------------------------ */
/*  AfriSpine Merchants — Single source of truth for merchant data    */
/* ------------------------------------------------------------------ */

export interface Merchant {
  id: string;
  name: string;
  slug: string;
  country: string;
  countryCode: string;
  category: MerchantCategory;
  logoUrl: string;
  description: string;
  isActive: boolean;
}

export const MERCH_CATEGORIES = [
  'Supermarket',
  'Electronics',
  'Fashion',
  'Airtime/Telecom',
  'Travel',
  'Food & Dining',
  'Healthcare',
  'Entertainment',
  'E-Commerce',
  'Utilities',
] as const;

export type MerchantCategory = (typeof MERCH_CATEGORIES)[number];

export const MERCH_COUNTRIES = [
  { code: 'KE', name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}' },
  { code: 'NG', name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}' },
  { code: 'ZA', name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}' },
  { code: 'GH', name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}' },
  { code: 'UG', name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}' },
  { code: 'TZ', name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}' },
] as const;

/* ================================================================== */
/*  KENYA (25 merchants)                                              */
/* ================================================================== */

const kenya: Merchant[] = [
  {
    id: 'ke-naivas',
    name: 'Naivas',
    slug: 'naivas',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/naivas.co.ke',
    description: 'Leading supermarket chain in Kenya with stores across the country.',
    isActive: true,
  },
  {
    id: 'ke-tuskys',
    name: 'Tuskys',
    slug: 'tuskys',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/tuskys.com',
    description: 'Tuskys Supermarket — one of Kenya\'s largest retail chains.',
    isActive: true,
  },
  {
    id: 'ke-quickmart',
    name: 'Quickmart',
    slug: 'quickmart',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/quickmart.co.ke',
    description: 'Fast-growing Kenyan supermarket chain.',
    isActive: true,
  },
  {
    id: 'ke-carrefour-kenya',
    name: 'Carrefour Kenya',
    slug: 'carrefour-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/carrefour.co.ke',
    description: 'International hypermarket and supermarket chain.',
    isActive: true,
  },
  {
    id: 'ke-safaricom',
    name: 'Safaricom',
    slug: 'safaricom',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/safaricom.co.ke',
    description: 'Kenya\'s leading telecom provider and M-Pesa pioneer.',
    isActive: true,
  },
  {
    id: 'ke-airtel-kenya',
    name: 'Airtel Kenya',
    slug: 'airtel-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/airtel.co.ke',
    description: 'Major mobile network operator in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-kenya-airways',
    name: 'Kenya Airways',
    slug: 'kenya-airways',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/kenya-airways.com',
    description: 'The Pride of Africa — Kenya\'s national carrier.',
    isActive: true,
  },
  {
    id: 'ke-java-house',
    name: 'Java House',
    slug: 'java-house',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/java-house.co.ke',
    description: 'Iconic East African coffee house and restaurant chain.',
    isActive: true,
  },
  {
    id: 'ke-artcaffe',
    name: 'Artcaffe',
    slug: 'artcaffe',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/artcaffe.co.ke',
    description: 'Premium coffee and dining restaurant chain in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-pizza-inn',
    name: 'Pizza Inn',
    slug: 'pizza-inn',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/pizzainn.co.ke',
    description: 'Popular pizza delivery and dine-in chain in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-deacons',
    name: 'Deacons',
    slug: 'deacons',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/deacons.co.ke',
    description: 'East Africa\'s leading fashion retail group — Mr Price, Adidas, Nike.',
    isActive: true,
  },
  {
    id: 'ke-woolworths-kenya',
    name: 'Woolworths Kenya',
    slug: 'woolworths-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/woolworths.co.ke',
    description: 'Premium fashion, food and beauty retailer.',
    isActive: true,
  },
  {
    id: 'ke-samsung-kenya',
    name: 'Samsung Kenya',
    slug: 'samsung-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/samsung.com/ke',
    description: 'Samsung electronics — phones, TVs, appliances in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-lg-kenya',
    name: 'LG Kenya',
    slug: 'lg-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/lg.com/ke',
    description: 'LG Electronics Kenya — home appliances and electronics.',
    isActive: true,
  },
  {
    id: 'ke-goodlife-pharmacy',
    name: 'Goodlife Pharmacy',
    slug: 'goodlife-pharmacy',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/goodlife.co.ke',
    description: 'Kenya\'s fastest-growing pharmacy chain.',
    isActive: true,
  },
  {
    id: 'ke-healthyu',
    name: 'HealthyU',
    slug: 'healthyu',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/healthyu.co.ke',
    description: 'Health and wellness products retailer in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-kplc',
    name: 'KPLC',
    slug: 'kplc',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Utilities',
    logoUrl: 'https://logo.clearbit.com/kplc.co.ke',
    description: 'Kenya Power and Lighting Company — prepaid tokens.',
    isActive: true,
  },
  {
    id: 'ke-dstv-kenya',
    name: 'DStv Kenya',
    slug: 'dstv-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.co.ke',
    description: 'DStv satellite TV subscriptions in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-showmax',
    name: 'Showmax',
    slug: 'showmax',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/showmax.com',
    description: 'African streaming service — movies, series and sports.',
    isActive: true,
  },
  {
    id: 'ke-uber-kenya',
    name: 'Uber Kenya',
    slug: 'uber-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/uber.com',
    description: 'Ride-hailing service in Nairobi and other Kenyan cities.',
    isActive: true,
  },
  {
    id: 'ke-bolt-kenya',
    name: 'Bolt Kenya',
    slug: 'bolt-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/bolt.eu',
    description: 'Affordable ride-hailing and food delivery in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-jumia-kenya',
    name: 'Jumia Kenya',
    slug: 'jumia-kenya',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/jumia.co.ke',
    description: 'Africa\'s leading online marketplace in Kenya.',
    isActive: true,
  },
  {
    id: 'ke-kilimall',
    name: 'Kilimall',
    slug: 'kilimall',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/kilimall.com',
    description: 'Online shopping mall focused on the African market.',
    isActive: true,
  },
  {
    id: 'ke-masoko',
    name: 'Masoko',
    slug: 'masoko',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/masoko.com',
    description: 'Safaricom\'s online shopping platform.',
    isActive: true,
  },
  {
    id: 'ke-chandarana',
    name: 'Chandarana',
    slug: 'chandarana',
    country: 'Kenya',
    countryCode: 'KE',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/chandarana.com',
    description: 'Premium supermarket chain in Kenya.',
    isActive: true,
  },
];

/* ================================================================== */
/*  NIGERIA (23 merchants)                                             */
/* ================================================================== */

const nigeria: Merchant[] = [
  {
    id: 'ng-shoprite',
    name: 'Shoprite Nigeria',
    slug: 'shoprite-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoprite.com.ng',
    description: 'Africa\'s largest supermarket chain in Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-jumia',
    name: 'Jumia Nigeria',
    slug: 'jumia-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/jumia.com.ng',
    description: 'Nigeria\'s leading online marketplace.',
    isActive: true,
  },
  {
    id: 'ng-konga',
    name: 'Konga',
    slug: 'konga',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/konga.com',
    description: 'Nigeria\'s premier online shopping destination.',
    isActive: true,
  },
  {
    id: 'ng-spar',
    name: 'SPAR Nigeria',
    slug: 'spar-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/spar.com.ng',
    description: 'International retail brand with stores across Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-payporte',
    name: 'Payporte',
    slug: 'payporte',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/payporte.com',
    description: 'Nigerian online fashion and lifestyle retailer.',
    isActive: true,
  },
  {
    id: 'ng-slot',
    name: 'Slot',
    slug: 'slot',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/slot.ng',
    description: 'Nigeria\'s leading mobile phone and electronics retailer.',
    isActive: true,
  },
  {
    id: 'ng-mtn',
    name: 'MTN Nigeria',
    slug: 'mtn-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/mtn.ng',
    description: 'Nigeria\'s largest telecom network with millions of subscribers.',
    isActive: true,
  },
  {
    id: 'ng-airtel-nigeria',
    name: 'Airtel Nigeria',
    slug: 'airtel-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/airtel.com.ng',
    description: 'Major mobile network operator in Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-glo',
    name: 'Glo',
    slug: 'glo',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/glo.com',
    description: 'Globacom — Nigeria\'s proudly Nigerian telecom network.',
    isActive: true,
  },
  {
    id: 'ng-9mobile',
    name: '9mobile',
    slug: '9mobile',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/9mobile.com.ng',
    description: 'Nigerian mobile network operator offering voice and data services.',
    isActive: true,
  },
  {
    id: 'ng-chicken-republic',
    name: 'Chicken Republic',
    slug: 'chicken-republic',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/chickenrepublic.com.ng',
    description: 'Nigeria\'s favourite quick-service chicken restaurant.',
    isActive: true,
  },
  {
    id: 'ng-dominos',
    name: "Domino's Pizza Nigeria",
    slug: 'dominos-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/dominos.com.ng',
    description: 'International pizza delivery chain in Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-coldstone',
    name: 'Coldstone Creamery',
    slug: 'coldstone',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/coldstonecreamery.com.ng',
    description: 'Premium ice cream parlour with Nigerian locations.',
    isActive: true,
  },
  {
    id: 'ng-hubmart',
    name: 'Hubmart',
    slug: 'hubmart',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/hubmart.com.ng',
    description: 'Modern supermarket chain in Lagos and beyond.',
    isActive: true,
  },
  {
    id: 'ng-justbuy',
    name: 'JustBuy',
    slug: 'justbuy',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/justbuy.com.ng',
    description: 'Online retail platform for electronics and home goods.',
    isActive: true,
  },
  {
    id: 'ng-max-air',
    name: 'Max Air',
    slug: 'max-air',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/maxair.com.ng',
    description: 'Nigerian airline offering domestic and regional flights.',
    isActive: true,
  },
  {
    id: 'ng-air-peace',
    name: 'Air Peace',
    slug: 'air-peace',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/airpeace.com',
    description: 'Nigeria\'s largest privately-owned airline.',
    isActive: true,
  },
  {
    id: 'ng-dana-air',
    name: 'Dana Air',
    slug: 'dana-air',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/danaair.com',
    description: 'Nigerian airline operating domestic scheduled flights.',
    isActive: true,
  },
  {
    id: 'ng-samsung-nigeria',
    name: 'Samsung Nigeria',
    slug: 'samsung-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/samsung.com/ng',
    description: 'Samsung electronics — phones, TVs and appliances in Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-lg-nigeria',
    name: 'LG Nigeria',
    slug: 'lg-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/lg.com/ng',
    description: 'LG Electronics Nigeria — home appliances and electronics.',
    isActive: true,
  },
  {
    id: 'ng-dstv-nigeria',
    name: 'DStv Nigeria',
    slug: 'dstv-nigeria',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    description: 'DStv satellite TV subscriptions in Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-gotv',
    name: 'GOtv',
    slug: 'gotv',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/gotvafrica.com',
    description: 'Affordable digital terrestrial TV across Nigeria.',
    isActive: true,
  },
  {
    id: 'ng-filmhouse',
    name: 'Filmhouse Cinemas',
    slug: 'filmhouse',
    country: 'Nigeria',
    countryCode: 'NG',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/filmhouseng.com',
    description: 'Nigeria\'s leading cinema chain with locations nationwide.',
    isActive: true,
  },
];

/* ================================================================== */
/*  SOUTH AFRICA (23 merchants)                                        */
/* ================================================================== */

const southAfrica: Merchant[] = [
  {
    id: 'za-shoprite',
    name: 'Shoprite SA',
    slug: 'shoprite-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoprite.co.za',
    description: 'Africa\'s largest supermarket retailer.',
    isActive: true,
  },
  {
    id: 'za-picknpay',
    name: 'Pick n Pay',
    slug: 'pick-n-pay',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/pnp.co.za',
    description: 'South Africa\'s favourite grocery retailer.',
    isActive: true,
  },
  {
    id: 'za-woolworths',
    name: 'Woolworths SA',
    slug: 'woolworths-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/woolworths.co.za',
    description: 'Premium fashion, food and beauty retailer.',
    isActive: true,
  },
  {
    id: 'za-spar',
    name: 'SPAR SA',
    slug: 'spar-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/spar.co.za',
    description: 'South Africa\'s leading independent grocery retailer.',
    isActive: true,
  },
  {
    id: 'za-checkers',
    name: 'Checkers',
    slug: 'checkers',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/checkers.co.za',
    description: 'Premium supermarket chain under the Shoprite group.',
    isActive: true,
  },
  {
    id: 'za-clicks',
    name: 'Clicks',
    slug: 'clicks',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/clicks.co.za',
    description: 'South Africa\'s leading health, beauty and pharmacy retailer.',
    isActive: true,
  },
  {
    id: 'za-dischem',
    name: 'Dis-Chem',
    slug: 'dis-chem',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/dischem.co.za',
    description: 'Specialist pharmacy and healthcare retailer.',
    isActive: true,
  },
  {
    id: 'za-mrprice',
    name: 'Mr Price',
    slug: 'mr-price',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/mrprice.com',
    description: 'Affordable fashion and sportswear retailer.',
    isActive: true,
  },
  {
    id: 'za-hm',
    name: 'H&M South Africa',
    slug: 'hm-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/hm.com',
    description: 'Global fashion brand with stores across South Africa.',
    isActive: true,
  },
  {
    id: 'za-cotton-on',
    name: 'Cotton On',
    slug: 'cotton-on',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/cottonon.com',
    description: 'Australian fashion brand popular in South Africa.',
    isActive: true,
  },
  {
    id: 'za-mtn-sa',
    name: 'MTN SA',
    slug: 'mtn-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/mtn.co.za',
    description: 'MTN South Africa — mobile network and data services.',
    isActive: true,
  },
  {
    id: 'za-vodacom',
    name: 'Vodacom',
    slug: 'vodacom',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/vodacom.com',
    description: 'South Africa\'s leading mobile network operator.',
    isActive: true,
  },
  {
    id: 'za-virgin-active',
    name: 'Virgin Active',
    slug: 'virgin-active',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/virginactive.co.za',
    description: 'Premium health club and gym chain.',
    isActive: true,
  },
  {
    id: 'za-nandos',
    name: "Nando's SA",
    slug: 'nandos-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/nandos.co.za',
    description: 'Legendary peri-peri chicken — born in South Africa.',
    isActive: true,
  },
  {
    id: 'za-debonairs',
    name: 'Debonairs Pizza',
    slug: 'debonairs',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/debonairspizza.co.za',
    description: 'South Africa\'s favourite pizza delivery chain.',
    isActive: true,
  },
  {
    id: 'za-wimpy',
    name: 'Wimpy',
    slug: 'wimpy',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/wimpy.co.za',
    description: 'Classic South African burger and breakfast chain.',
    isActive: true,
  },
  {
    id: 'za-dstv-sa',
    name: 'DStv SA',
    slug: 'dstv-sa',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    description: 'Multichoice DStv — premium satellite TV in South Africa.',
    isActive: true,
  },
  {
    id: 'za-multichoice',
    name: 'MultiChoice',
    slug: 'multichoice',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/multichoice.com',
    description: 'Africa\'s leading entertainment and video content company.',
    isActive: true,
  },
  {
    id: 'za-takealot',
    name: 'Takealot',
    slug: 'takealot',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/takealot.com',
    description: 'South Africa\'s largest online retailer.',
    isActive: true,
  },
  {
    id: 'za-superbalist',
    name: 'Superbalist',
    slug: 'superbalist',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/superbalist.com',
    description: 'South Africa\'s leading online fashion destination.',
    isActive: true,
  },
  {
    id: 'za-zando',
    name: 'Zando',
    slug: 'zando',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Fashion',
    logoUrl: 'https://logo.clearbit.com/zando.co.za',
    description: 'Online fashion and lifestyle retailer in South Africa.',
    isActive: true,
  },
  {
    id: 'za-flysafair',
    name: 'FlySafair',
    slug: 'flysafair',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/flysafair.co.za',
    description: 'South Africa\'s favourite low-cost airline.',
    isActive: true,
  },
  {
    id: 'za-discovery',
    name: 'Discovery Health',
    slug: 'discovery-health',
    country: 'South Africa',
    countryCode: 'ZA',
    category: 'Healthcare',
    logoUrl: 'https://logo.clearbit.com/discovery.co.za',
    description: 'South Africa\'s leading health insurance and wellness company.',
    isActive: true,
  },
];

/* ================================================================== */
/*  GHANA (18 merchants)                                               */
/* ================================================================== */

const ghana: Merchant[] = [
  {
    id: 'gh-melcom',
    name: 'Melcom',
    slug: 'melcom',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/melcom.com',
    description: 'Ghana\'s largest retail and department store chain.',
    isActive: true,
  },
  {
    id: 'gh-shoprite',
    name: 'Shoprite Ghana',
    slug: 'shoprite-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoprite.com.gh',
    description: 'International supermarket chain in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-marina-mall',
    name: 'Marina Mall',
    slug: 'marina-mall',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/marinamall.com.gh',
    description: 'Premium shopping destination in Accra.',
    isActive: true,
  },
  {
    id: 'gh-maxmart',
    name: 'MaxMart',
    slug: 'maxmart',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/maxmartghana.com',
    description: 'One of Ghana\'s leading supermarket chains.',
    isActive: true,
  },
  {
    id: 'gh-koala',
    name: 'Koala',
    slug: 'koala',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/koala.com.gh',
    description: 'Premium supermarket and grocery store in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-mtn',
    name: 'MTN Ghana',
    slug: 'mtn-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/mtn.com.gh',
    description: 'Ghana\'s largest mobile network operator.',
    isActive: true,
  },
  {
    id: 'gh-vodafone',
    name: 'Vodafone Ghana',
    slug: 'vodafone-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/vodafone.com.gh',
    description: 'Telecommunications provider in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-airteltigo',
    name: 'AirtelTigo',
    slug: 'airteltigo',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/airteltigo.com.gh',
    description: 'Merged mobile network operator in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-glo-ghana',
    name: 'Glo Ghana',
    slug: 'glo-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/glo.com.gh',
    description: 'Globacom telecommunications in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-kfc-ghana',
    name: 'KFC Ghana',
    slug: 'kfc-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/kfc.com.gh',
    description: 'KFC fried chicken restaurants in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-pizza-hut',
    name: 'Pizza Hut Ghana',
    slug: 'pizza-hut-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/pizzahut.com.gh',
    description: 'International pizza chain with locations in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-epp-books',
    name: 'EPP Books',
    slug: 'epp-books',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/eppbookservices.com',
    description: 'Ghana\'s leading bookshop and educational materials supplier.',
    isActive: true,
  },
  {
    id: 'gh-starbow',
    name: 'Starbow',
    slug: 'starbow',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/flystarbow.com',
    description: 'Ghanaian domestic airline.',
    isActive: true,
  },
  {
    id: 'gh-awa',
    name: 'Africa World Airlines',
    slug: 'africa-world-airlines',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Travel',
    logoUrl: 'https://logo.clearbit.com/flyawa.com',
    description: 'Ghana\'s largest domestic airline.',
    isActive: true,
  },
  {
    id: 'gh-samsung-ghana',
    name: 'Samsung Ghana',
    slug: 'samsung-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/samsung.com/gh',
    description: 'Samsung electronics in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-dstv-ghana',
    name: 'DStv Ghana',
    slug: 'dstv-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    description: 'DStv satellite TV subscriptions in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-jumia-ghana',
    name: 'Jumia Ghana',
    slug: 'jumia-ghana',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/jumia.com.gh',
    description: 'Online marketplace for shopping in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-hubtel',
    name: 'Hubtel',
    slug: 'hubtel',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Utilities',
    logoUrl: 'https://logo.clearbit.com/hubtel.com',
    description: 'Ghana\'s leading mobile payments and commerce platform.',
    isActive: true,
  },
  {
    id: 'gh-zeepay',
    name: 'Zeepay',
    slug: 'zeepay',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Utilities',
    logoUrl: 'https://logo.clearbit.com/zeepay.com.gh',
    description: 'Mobile money and digital payments platform in Ghana.',
    isActive: true,
  },
  {
    id: 'gh-palace-mall',
    name: 'Palace Mall',
    slug: 'palace-mall',
    country: 'Ghana',
    countryCode: 'GH',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/palacemallspintex.com',
    description: 'Shopping mall and retail centre in Accra.',
    isActive: true,
  },
];

/* ================================================================== */
/*  UGANDA (15 merchants)                                              */
/* ================================================================== */

const uganda: Merchant[] = [
  {
    id: 'ug-shoprite',
    name: 'Shoprite Uganda',
    slug: 'shoprite-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoprite.ug',
    description: 'Africa\'s largest supermarket chain in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-capital-shoppers',
    name: 'Capital Shoppers',
    slug: 'capital-shoppers',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/capitalshoppers.co.ug',
    description: 'Leading supermarket chain in Kampala.',
    isActive: true,
  },
  {
    id: 'ug-quality-supermarket',
    name: 'Quality Supermarket',
    slug: 'quality-supermarket',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/qualitysupermarket.ug',
    description: 'Premium grocery store in Kampala, Uganda.',
    isActive: true,
  },
  {
    id: 'ug-uchumi',
    name: 'Uchumi Uganda',
    slug: 'uchumi-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/uchumi.co.ke',
    description: 'East African supermarket chain with Uganda presence.',
    isActive: true,
  },
  {
    id: 'ug-mtn',
    name: 'MTN Uganda',
    slug: 'mtn-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/mtn.co.ug',
    description: 'Uganda\'s largest mobile network operator.',
    isActive: true,
  },
  {
    id: 'ug-airtel-uganda',
    name: 'Airtel Uganda',
    slug: 'airtel-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/airtel.co.ug',
    description: 'Major telecom provider in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-utl',
    name: 'Uganda Telecom',
    slug: 'uganda-telecom',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/utl.co.ug',
    description: 'Uganda\'s national telecommunications company.',
    isActive: true,
  },
  {
    id: 'ug-simba-telecom',
    name: 'Simba Telecom',
    slug: 'simba-telecom',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/simbatelecom.co.ug',
    description: 'Uganda\'s largest mobile phone and accessories retailer.',
    isActive: true,
  },
  {
    id: 'ug-pizza-hut',
    name: 'Pizza Hut Uganda',
    slug: 'pizza-hut-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/pizzahut.co.ug',
    description: 'International pizza chain in Kampala.',
    isActive: true,
  },
  {
    id: 'ug-kfc',
    name: 'KFC Uganda',
    slug: 'kfc-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/kfc.co.ug',
    description: 'KFC restaurants in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-jumia',
    name: 'Jumia Uganda',
    slug: 'jumia-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/jumia.co.ug',
    description: 'Online marketplace for shopping in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-samsung-uganda',
    name: 'Samsung Uganda',
    slug: 'samsung-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/samsung.com/ug',
    description: 'Samsung electronics in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-dstv',
    name: 'DStv Uganda',
    slug: 'dstv-uganda',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    description: 'DStv satellite TV subscriptions in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-century-bottling',
    name: 'Century Bottling',
    slug: 'century-bottling',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/ccbuganda.com',
    description: 'Coca-Cola bottling company in Uganda.',
    isActive: true,
  },
  {
    id: 'ug-fresh-cuts',
    name: 'Fresh Cuts',
    slug: 'fresh-cuts',
    country: 'Uganda',
    countryCode: 'UG',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/freshcuts.co.ug',
    description: 'Popular Ugandan restaurant and butchery chain.',
    isActive: true,
  },
];

/* ================================================================== */
/*  TANZANIA (14 merchants)                                            */
/* ================================================================== */

const tanzania: Merchant[] = [
  {
    id: 'tz-shoprite',
    name: 'Shoprite Tanzania',
    slug: 'shoprite-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoprite.co.tz',
    description: 'Africa\'s largest supermarket chain in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-shoppers-plaza',
    name: 'Shoppers Plaza',
    slug: 'shoppers-plaza',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/shoppersplaza.co.tz',
    description: 'Shopping centre and supermarket in Dar es Salaam.',
    isActive: true,
  },
  {
    id: 'tz-uchumi-tz',
    name: 'Uchumi Tanzania',
    slug: 'uchumi-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/uchumi.co.ke',
    description: 'East African supermarket chain with Tanzania presence.',
    isActive: true,
  },
  {
    id: 'tz-naivas-tz',
    name: 'Naivas Tanzania',
    slug: 'naivas-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Supermarket',
    logoUrl: 'https://logo.clearbit.com/naivas.co.ke',
    description: 'Kenyan supermarket chain expanding into Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-mpesa',
    name: 'M-Pesa Tanzania',
    slug: 'mpesa-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/mpesa.co.tz',
    description: 'Vodacom M-Pesa mobile money in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-vodacom',
    name: 'Vodacom Tanzania',
    slug: 'vodacom-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/vodacom.co.tz',
    description: 'Tanzania\'s leading mobile network operator.',
    isActive: true,
  },
  {
    id: 'tz-airtel-tz',
    name: 'Airtel Tanzania',
    slug: 'airtel-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/airtel.co.tz',
    description: 'Major telecom provider in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-tigo',
    name: 'Tigo',
    slug: 'tigo',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/tigo.co.tz',
    description: 'Mobile network and mobile money provider in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-halotel',
    name: 'Halotel',
    slug: 'halotel',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Airtime/Telecom',
    logoUrl: 'https://logo.clearbit.com/halotel.co.tz',
    description: 'Tanzanian mobile network operator.',
    isActive: true,
  },
  {
    id: 'tz-pizza-hut-tz',
    name: 'Pizza Hut Tanzania',
    slug: 'pizza-hut-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/pizzahut.co.tz',
    description: 'International pizza chain in Dar es Salaam.',
    isActive: true,
  },
  {
    id: 'tz-kfc-tz',
    name: 'KFC Tanzania',
    slug: 'kfc-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Food & Dining',
    logoUrl: 'https://logo.clearbit.com/kfc.co.tz',
    description: 'KFC restaurants in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-jumia-tz',
    name: 'Jumia Tanzania',
    slug: 'jumia-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'E-Commerce',
    logoUrl: 'https://logo.clearbit.com/jumia.co.tz',
    description: 'Online marketplace for shopping in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-samsung-tz',
    name: 'Samsung Tanzania',
    slug: 'samsung-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Electronics',
    logoUrl: 'https://logo.clearbit.com/samsung.com/tz',
    description: 'Samsung electronics in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-dstv-tz',
    name: 'DStv Tanzania',
    slug: 'dstv-tanzania',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    description: 'DStv satellite TV subscriptions in Tanzania.',
    isActive: true,
  },
  {
    id: 'tz-azam-tv',
    name: 'Azam TV',
    slug: 'azam-tv',
    country: 'Tanzania',
    countryCode: 'TZ',
    category: 'Entertainment',
    logoUrl: 'https://logo.clearbit.com/azamtv.com',
    description: 'Affordable digital TV service across East Africa.',
    isActive: true,
  },
];

/* ================================================================== */
/*  COMBINED EXPORTS                                                  */
/* ================================================================== */

/** All active merchants across all countries */
export const allMerchants: Merchant[] = [
  ...kenya,
  ...nigeria,
  ...southAfrica,
  ...ghana,
  ...uganda,
  ...tanzania,
].filter((m) => m.isActive);

/** Get merchants filtered by country code (e.g. 'KE', 'NG') */
export function getMerchantsByCountry(countryCode: string): Merchant[] {
  return allMerchants.filter(
    (m) => m.countryCode.toUpperCase() === countryCode.toUpperCase(),
  );
}

/** Get merchants filtered by category */
export function getMerchantsByCategory(category: string): Merchant[] {
  return allMerchants.filter(
    (m) => m.category.toLowerCase() === category.toLowerCase(),
  );
}

/** Get a single merchant by ID */
export function getMerchantById(id: string): Merchant | undefined {
  return allMerchants.find((m) => m.id === id);
}

/** A curated set of featured merchants to display on marketing pages */
export const featuredMerchants: Merchant[] = [
  allMerchants.find((m) => m.id === 'ke-naivas')!,
  allMerchants.find((m) => m.id === 'ng-jumia')!,
  allMerchants.find((m) => m.id === 'za-shoprite')!,
  allMerchants.find((m) => m.id === 'gh-melcom')!,
  allMerchants.find((m) => m.id === 'ke-safaricom')!,
  allMerchants.find((m) => m.id === 'za-picknpay')!,
  allMerchants.find((m) => m.id === 'ng-mtn')!,
  allMerchants.find((m) => m.id === 'za-takealot')!,
  allMerchants.find((m) => m.id === 'ke-kenya-airways')!,
  allMerchants.find((m) => m.id === 'ng-chicken-republic')!,
  allMerchants.find((m) => m.id === 'za-nandos')!,
  allMerchants.find((m) => m.id === 'gh-mtn')!,
].filter(Boolean);